# Builds the firmware with arm-none-eabi-gcc, without STM32CubeIDE.
#
# The flags mirror the ones CubeIDE uses (see a CubeIDE build log), so the result should match. 
# This file exists so the project can be built from a clean checkout -- CubeIDE's generated makefile lives in Debug/, 
# which is not committed, and contains absolute paths from the machine that generated it.
#
#   make              Debug build   (-O0, DEBUG defined, CRASH commands present)
#   make RELEASE=1    Release build (-Os, DEBUG undefined, CRASH commands removed)
#   make clean

TARGET   = FelineGuard

CC       = arm-none-eabi-gcc
SIZE     = arm-none-eabi-size

ifeq ($(RELEASE),1)
  CONFIG = release
  OPT    = -Os
  DBG    =
else
  CONFIG = debug
  OPT    = -O0
  DBG    = -g3 -DDEBUG
endif

BUILD    = build/$(CONFIG)

# ---------- sources ----------
# Found by wildcard, so adding or removing a .c file needs no edit here.
# A directory that does not exist (FreeRTOS/ on the superloop branch) simply contributes nothing.
SRC_DIRS = Application/Src Driver/Src Executive System/Src HAL/Src FreeRTOS/Src
C_SRCS   = $(foreach d,$(SRC_DIRS),$(wildcard $(d)/*.c))
S_SRCS   = $(wildcard Startup/*.s)

OBJS     = $(addprefix $(BUILD)/,$(C_SRCS:.c=.o) $(S_SRCS:.s=.o))

# ---------- flags ----------
CPU      = -mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=hard

DEFS     = -DUSE_HAL_DRIVER -DSTM32F446xx -DSTM32 -DSTM32F4 -DSTM32F446RETx

INCS     = -ICMSIS/Include \
           -ICMSIS/Device/ST/STM32F4xx/Include \
           -IHAL/Inc \
           -ISystem/Inc \
           -IDriver/Inc \
           -IApplication/Inc \
           -IFreeRTOS/Inc

CFLAGS   = $(CPU) -std=gnu11 $(OPT) $(DBG) $(DEFS) $(INCS) \
           -ffunction-sections -fdata-sections -Wall -fstack-usage \
           --specs=nano.specs -MMD -MP

ASFLAGS  = $(CPU) $(DBG) -x assembler-with-cpp --specs=nano.specs

LDSCRIPT = STM32F446RETX_FLASH.ld
LDFLAGS  = $(CPU) -T$(LDSCRIPT) --specs=nosys.specs --specs=nano.specs \
           -Wl,-Map=$(BUILD)/$(TARGET).map -Wl,--gc-sections -static \
           -Wl,--start-group -lc -lm -Wl,--end-group

# ---------- rules ----------
all: $(BUILD)/$(TARGET).elf

$(BUILD)/$(TARGET).elf: $(OBJS)
	$(CC) $(OBJS) $(LDFLAGS) -o $@
	$(SIZE) $@

$(BUILD)/%.o: %.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -c $< -o $@

$(BUILD)/%.o: %.s
	@mkdir -p $(dir $@)
	$(CC) $(ASFLAGS) -c $< -o $@

clean:
	rm -rf build

# Header dependencies generated by -MMD, so editing a .h rebuilds what uses it.
-include $(OBJS:.o=.d)

.PHONY: all clean